# Generated by Django 4.2.6 on 2024-02-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='site/', verbose_name='Banner Image')),
                ('caption', models.TextField(verbose_name='Caption')),
            ],
        ),
    ]
